// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trbcpwqvtbieaofirmbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYmNwd3F2dGJpZWFvZmlybWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTc1MzUsImV4cCI6MjA2OTE3MzUzNX0.r7X4gR11FijzE2RFn2tBIc6m4L10qTR2OsFYNgX3GWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});